import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Knock Knock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div id="header-area">
          안녕하세요 Knock Knock에 오신 여러분을 환영합니다.
        </div>
        <h1>
          <a href="/">WEB</a>
        </h1>
        {children}
        <ul>
          <Link href="/read/1">Read</Link>
        </ul>

        <footer></footer>
      </body>
    </html>
  );
}
